package se.linkon.service.timetable.v2_7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-29T15:03:29.466+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://service.linkon.se/timetable/v2_7", name = "Timetable-service")
@XmlSeeAlso({org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, se.linkon.petra.commoncomplexelements.data.v4_6.ObjectFactory.class, se.linkon.petra.commonelements.data.v4_6.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class, se.linkon.petra.timetable.data.v2_7.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TimetableService {

    /**
     * This operation returns all the travel methods the client is allowed to handle in the getTimetable request. 
     * If the client wants to reduce travel methods in the timetable response, it can exclude one or several travel methods from the getTimetable query.
     * 
     * This response shall be locally cached due to the result is quite big and will be the same all day. Recommended expiration time for the cache is 06.00.
     *  
     */
    @WebMethod
    @WebResult(name = "AcceptableTravelMethods", targetNamespace = "http://petra.linkon.se/timetable/data/v2_7", partName = "result")
    public se.linkon.petra.timetable.data.v2_7.AcceptableTravelMethods getAcceptableTravelMethods(
        @WebParam(partName = "parameters", name = "AcceptableTravelMethodsQuery", targetNamespace = "http://petra.linkon.se/timetable/data/v2_7")
        se.linkon.petra.timetable.data.v2_7.AcceptableTravelMethodsQuery parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws TimetableException;

    /**
     * This operation is used to get timetable information between two locations in the Petra2Service system.
     * The result of the operation is a list of journey advices between the given departure and arrival locations for the given time. 
     * The query has several optional items for tuning the Timetable response. 
     * The repose contains a list of journey advices holding 1-n Itineries. Each itinerary hold 1-n segments.
     * Example of journey advices for Arboga stn - Lulea airport
     * Journey advice1:
     *    Itinerary1: 
     *      Segment1: Arboga stn 05:15 - Arlanda       07:16 SJ Train
     *    Itinerary2:
     *      Segment1: Arlanda    08:15 - Lulea airport 09:35 SAS Aeroplane 
     * Journey advice2:
     *    Itinerary1: 
     *      Segment1: Arboga stn 11:21 - Balsta stn    12:22 SJ Train
     *      Segment2: Balsta stn 12:35 - Arlanda       13:28 UL Buss
     *    Itinerary2:
     *      Segment1: Arlanda    15:10 - Lulea airport 16:30 SAS Aeroplane 
     *  
     */
    @WebMethod
    @WebResult(name = "Timetable", targetNamespace = "http://petra.linkon.se/timetable/data/v2_7", partName = "result")
    public se.linkon.petra.timetable.data.v2_7.Timetable getTimetable(
        @WebParam(partName = "parameters", name = "TimetableQuery", targetNamespace = "http://petra.linkon.se/timetable/data/v2_7")
        se.linkon.petra.timetable.data.v2_7.TimetableQuery parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws TimetableException;

    /**
     * This method can be used to resolve text strings given a valid code.
     */
    @WebMethod
    @WebResult(name = "GetValidCodesResponse", targetNamespace = "http://petra.linkon.se/timetable/data/v2_7", partName = "result")
    public se.linkon.petra.timetable.data.v2_7.GetValidCodesResponse getValidCodes(
        @WebParam(partName = "parameters", name = "GetValidCodesRequest", targetNamespace = "http://petra.linkon.se/timetable/data/v2_7")
        se.linkon.petra.timetable.data.v2_7.GetValidCodesRequest parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws TimetableException;
}
