
package se.linkon.service.timetable.v2_7;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-29T15:03:29.428+01:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "TimetableExceptionData", targetNamespace = "http://petra.linkon.se/timetable/data/v2_7")
public class TimetableException extends Exception {
    
    private se.linkon.petra.timetable.data.v2_7.TimetableExceptionData timetableExceptionData;

    public TimetableException() {
        super();
    }
    
    public TimetableException(String message) {
        super(message);
    }
    
    public TimetableException(String message, Throwable cause) {
        super(message, cause);
    }

    public TimetableException(String message, se.linkon.petra.timetable.data.v2_7.TimetableExceptionData timetableExceptionData) {
        super(message);
        this.timetableExceptionData = timetableExceptionData;
    }

    public TimetableException(String message, se.linkon.petra.timetable.data.v2_7.TimetableExceptionData timetableExceptionData, Throwable cause) {
        super(message, cause);
        this.timetableExceptionData = timetableExceptionData;
    }

    public se.linkon.petra.timetable.data.v2_7.TimetableExceptionData getFaultInfo() {
        return this.timetableExceptionData;
    }
}
