package se.linkon.service.timetable.v2_7;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-29T15:03:29.525+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "WSTimetableService", 
                  wsdlLocation = "classpath:wsdl/timetable/2_7/TimetableService.wsdl",
                  targetNamespace = "http://service.linkon.se/timetable/v2_7") 
public class WSTimetableService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.linkon.se/timetable/v2_7", "WSTimetableService");
    public final static QName WSTimetablePort = new QName("http://service.linkon.se/timetable/v2_7", "WSTimetable-port");
    static {
        URL url = WSTimetableService.class.getClassLoader().getResource("wsdl/timetable/2_7/TimetableService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(WSTimetableService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/timetable/2_7/TimetableService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public WSTimetableService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSTimetableService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTimetableService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSTimetableService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSTimetableService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSTimetableService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TimetableService
     */
    @WebEndpoint(name = "WSTimetable-port")
    public TimetableService getWSTimetablePort() {
        return super.getPort(WSTimetablePort, TimetableService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimetableService
     */
    @WebEndpoint(name = "WSTimetable-port")
    public TimetableService getWSTimetablePort(WebServiceFeature... features) {
        return super.getPort(WSTimetablePort, TimetableService.class, features);
    }

}
