
package se.linkon.service.order.orderstorage.v1_10;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-29T15:05:07.048+01:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "OrderStorageExceptionData", targetNamespace = "http://petra.linkon.se/order/orderstorage/data/v1_10")
public class OrderStorageException extends Exception {
    
    private se.linkon.petra.order.orderstorage.data.v1_10.OrderStorageExceptionData orderStorageExceptionData;

    public OrderStorageException() {
        super();
    }
    
    public OrderStorageException(String message) {
        super(message);
    }
    
    public OrderStorageException(String message, Throwable cause) {
        super(message, cause);
    }

    public OrderStorageException(String message, se.linkon.petra.order.orderstorage.data.v1_10.OrderStorageExceptionData orderStorageExceptionData) {
        super(message);
        this.orderStorageExceptionData = orderStorageExceptionData;
    }

    public OrderStorageException(String message, se.linkon.petra.order.orderstorage.data.v1_10.OrderStorageExceptionData orderStorageExceptionData, Throwable cause) {
        super(message, cause);
        this.orderStorageExceptionData = orderStorageExceptionData;
    }

    public se.linkon.petra.order.orderstorage.data.v1_10.OrderStorageExceptionData getFaultInfo() {
        return this.orderStorageExceptionData;
    }
}
