package se.linkon.service.order.orderstorage.v1_10;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-29T15:05:07.106+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "WSOrderStorageService", 
                  wsdlLocation = "classpath:wsdl/orderstorage/1_10/OrderStorageService.wsdl",
                  targetNamespace = "http://service.linkon.se/order/orderstorage/v1_10") 
public class WSOrderStorageService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.linkon.se/order/orderstorage/v1_10", "WSOrderStorageService");
    public final static QName WSOrderStoragePort = new QName("http://service.linkon.se/order/orderstorage/v1_10", "WSOrderStorage-port");
    static {
        URL url = WSOrderStorageService.class.getClassLoader().getResource("wsdl/orderstorage/1_10/OrderStorageService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(WSOrderStorageService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/orderstorage/1_10/OrderStorageService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public WSOrderStorageService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSOrderStorageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSOrderStorageService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSOrderStorageService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSOrderStorageService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSOrderStorageService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrderStorageService
     */
    @WebEndpoint(name = "WSOrderStorage-port")
    public OrderStorageService getWSOrderStoragePort() {
        return super.getPort(WSOrderStoragePort, OrderStorageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderStorageService
     */
    @WebEndpoint(name = "WSOrderStorage-port")
    public OrderStorageService getWSOrderStoragePort(WebServiceFeature... features) {
        return super.getPort(WSOrderStoragePort, OrderStorageService.class, features);
    }

}
