
package se.linkon.service.location.v1_5;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-29T15:03:20.888+01:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "LocationExceptionData", targetNamespace = "http://petra.linkon.se/location/data/v1_5")
public class LocationException extends Exception {
    
    private se.linkon.petra.location.data.v1_5.LocationExceptionData locationExceptionData;

    public LocationException() {
        super();
    }
    
    public LocationException(String message) {
        super(message);
    }
    
    public LocationException(String message, Throwable cause) {
        super(message, cause);
    }

    public LocationException(String message, se.linkon.petra.location.data.v1_5.LocationExceptionData locationExceptionData) {
        super(message);
        this.locationExceptionData = locationExceptionData;
    }

    public LocationException(String message, se.linkon.petra.location.data.v1_5.LocationExceptionData locationExceptionData, Throwable cause) {
        super(message, cause);
        this.locationExceptionData = locationExceptionData;
    }

    public se.linkon.petra.location.data.v1_5.LocationExceptionData getFaultInfo() {
        return this.locationExceptionData;
    }
}
