
package se.linkon.service.gtssales.v1_17;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-29T15:04:03.672+01:00
 * Generated source version: 3.1.8
 */

@WebFault(name = "GtsSalesExceptionData", targetNamespace = "http://petra.linkon.se/gtssales/data/v1_17")
public class GtsSalesException extends Exception {
    
    private se.linkon.petra.gtssales.data.v1_17.GtsSalesExceptionData gtsSalesExceptionData;

    public GtsSalesException() {
        super();
    }
    
    public GtsSalesException(String message) {
        super(message);
    }
    
    public GtsSalesException(String message, Throwable cause) {
        super(message, cause);
    }

    public GtsSalesException(String message, se.linkon.petra.gtssales.data.v1_17.GtsSalesExceptionData gtsSalesExceptionData) {
        super(message);
        this.gtsSalesExceptionData = gtsSalesExceptionData;
    }

    public GtsSalesException(String message, se.linkon.petra.gtssales.data.v1_17.GtsSalesExceptionData gtsSalesExceptionData, Throwable cause) {
        super(message, cause);
        this.gtsSalesExceptionData = gtsSalesExceptionData;
    }

    public se.linkon.petra.gtssales.data.v1_17.GtsSalesExceptionData getFaultInfo() {
        return this.gtsSalesExceptionData;
    }
}
