package se.linkon.service.gtssales.v1_17;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Public ground travel service for the sales domain
 *         
 *
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-29T15:04:03.676+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://service.linkon.se/gtssales/v1_17", name = "GtsSales-service")
@XmlSeeAlso({se.linkon.petra.gtssales.placementoptions.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.optionavailability.data.v1_17.ObjectFactory.class, se.linkon.petra.commoncomplexelements.data.v4_6.ObjectFactory.class, se.linkon.petra.gtssales.passengercategories.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.pricegroups.data.v1_17.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class, se.linkon.petra.gtssales.changedeparture.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.shared.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.journeyadvicepricequotes.detailed.data.v1_17.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, se.linkon.petra.commonelements.data.v4_6.ObjectFactory.class, se.linkon.petra.gtssales.journeyadvicepricequotes.shared.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.validatepromotioncode.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.journeyadvicepricequotes.overview.data.v1_17.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class, se.linkon.petra.gtssales.edittransport.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.booktransport.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.seatavailability.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.itinerarycharacteristics.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.validpricegroups.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.seatavailability.detail.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.transportactions.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.multiridealternativerelations.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.validcodes.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.detailedpricequote.data.v1_17.ObjectFactory.class, se.linkon.petra.gtssales.data.v1_17.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GtsSalesService {

    /**
     * The operation returns valid pricegroups, optionally appending
     * information
     * concerning accumulators (antalsraknare), seat availability and prices, for
     * the given itineraries.
     *               
     */
    @WebMethod
    @WebResult(name = "GetValidPriceGroupsDescription", targetNamespace = "http://petra.linkon.se/gtssales/validpricegroups/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.validpricegroups.data.v1_17.GetValidPriceGroupsDescription getValidPriceGroups(
        @WebParam(partName = "parameters", name = "GetValidPriceGroupsSpecification", targetNamespace = "http://petra.linkon.se/gtssales/validpricegroups/data/v1_17")
        se.linkon.petra.gtssales.validpricegroups.data.v1_17.GetValidPriceGroupsSpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation returns the itinerary characteristics for the itinerary
     * in the
     * request.
     *             
     */
    @WebMethod
    @WebResult(name = "GetItineraryCharacteristicsResponse", targetNamespace = "http://petra.linkon.se/gtssales/itinerarycharacteristics/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.itinerarycharacteristics.data.v1_17.GetItineraryCharacteristicsResponse getItineraryCharacteristics(
        @WebParam(partName = "parameters", name = "GetItineraryCharacteristicsSpecification", targetNamespace = "http://petra.linkon.se/gtssales/itinerarycharacteristics/data/v1_17")
        se.linkon.petra.gtssales.itinerarycharacteristics.data.v1_17.GetItineraryCharacteristicsSpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation edits an existing transport booking according to the
     * request.
     * Bookings can be altered in various ways, for instance by removing or adding
     * a
     * new service (component) or by modifying an existing service
     * (component).
     *             
     */
    @WebMethod
    @WebResult(name = "EditTransportDescription", targetNamespace = "http://petra.linkon.se/gtssales/edittransport/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.edittransport.data.v1_17.EditTransportDescription editTransport(
        @WebParam(partName = "parameters", name = "EditTransportSpecification", targetNamespace = "http://petra.linkon.se/gtssales/edittransport/data/v1_17")
        se.linkon.petra.gtssales.edittransport.data.v1_17.EditTransportSpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation returns the available edit actions for an existing
     * transport booking.
     *             
     */
    @WebMethod
    @WebResult(name = "GetTransportActionsResponse", targetNamespace = "http://petra.linkon.se/gtssales/transportactions/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.transportactions.data.v1_17.GetTransportActionsResponse getTransportActions(
        @WebParam(partName = "parameters", name = "GetTransportActionsSpecification", targetNamespace = "http://petra.linkon.se/gtssales/transportactions/data/v1_17")
        se.linkon.petra.gtssales.transportactions.data.v1_17.GetTransportActionsSpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation books a segment according to the request.
     *             
     */
    @WebMethod
    @WebResult(name = "BookSegmentDescription", targetNamespace = "http://petra.linkon.se/gtssales/booktransport/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.booktransport.data.v1_17.BookSegmentDescription bookSegment(
        @WebParam(partName = "parameters", name = "BookSegmentSpecification", targetNamespace = "http://petra.linkon.se/gtssales/booktransport/data/v1_17")
        se.linkon.petra.gtssales.booktransport.data.v1_17.BookSegmentSpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * Returns valid, but not necessarily available, placement options for a requested journey. 
     * The placement options are returned for the different levels of the journey;
     * The valid options for each segment, aggregated on itinerary level, and 
     * aggregated for the journey as a whole.
     * The aggregations are done according to a intersection kind of strategy, meaning for example that
     * only placement options valid for all segment of an itinerary will be present on the itinerary level.
     * However, segments that does not support booking, for example if BookingRule is EJBO, will NOT be regarded
     * in this intersection strategy and will not have any impact on the Placement Options on the itinerary level.
     * Only Placement Options available for all the journey's consumers will be returned. 
     * This means that a journey with two consumers, containing a segment were there's only one placement left
     * for each of the segment's placement types, will return empty lists of placement options. 
     * 
     */
    @WebMethod
    @WebResult(name = "GetPlacementOptionsResponse", targetNamespace = "http://petra.linkon.se/gtssales/placementoptions/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.placementoptions.data.v1_17.GetPlacementOptionsResponse getPlacementOptions(
        @WebParam(partName = "parameters", name = "GetPlacementOptionsRequest", targetNamespace = "http://petra.linkon.se/gtssales/placementoptions/data/v1_17")
        se.linkon.petra.gtssales.placementoptions.data.v1_17.GetPlacementOptionsRequest parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation gets a detailed price quote for an itinerary according to the request.
     */
    @WebMethod
    @WebResult(name = "DetailedItineraryPriceQuoteResponse", targetNamespace = "http://petra.linkon.se/gtssales/detailedpricequote/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.detailedpricequote.data.v1_17.DetailedItineraryPriceQuoteResponse detailedItineraryPriceQuote(
        @WebParam(partName = "parameters", name = "DetailedItineraryPriceQuoteQuery", targetNamespace = "http://petra.linkon.se/gtssales/detailedpricequote/data/v1_17")
        se.linkon.petra.gtssales.detailedpricequote.data.v1_17.DetailedItineraryPriceQuoteQuery parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation changes departure, if possible, according to the request.
     *             
     */
//    @WebMethod
//    @WebResult(name = "ChangeDepartureDescription", targetNamespace = "http://petra.linkon.se/gtssales/changedeparture/data/v1_17", partName = "result")
//    public se.linkon.petra.gtssales.changedeparture.data.v1_17.ChangeDepartureDescription changeDeparture(
//        @WebParam(partName = "parameters", name = "ChangeDepartureSpecification", targetNamespace = "http://petra.linkon.se/gtssales/changedeparture/data/v1_17")
//        se.linkon.petra.gtssales.changedeparture.data.v1_17.ChangeDepartureSpecification parameters,
//        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6")
//        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
//    ) throws GtsSalesException;

    /**
     * The operation returns an overview journey advice price quote using sales
     * categories.
     *               
     */
    @WebMethod
    @WebResult(name = "GetJourneyAdviceOverviewPriceQuotesDescription", targetNamespace = "http://petra.linkon.se/gtssales/journeyadvicepricequotes/overview/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.journeyadvicepricequotes.overview.data.v1_17.GetJourneyAdviceOverviewPriceQuotesDescription getJourneyAdviceOverviewPriceQuotes(
        @WebParam(partName = "parameters", name = "GetJourneyAdviceOverviewPriceQuotesSpecification", targetNamespace = "http://petra.linkon.se/gtssales/journeyadvicepricequotes/overview/data/v1_17")
        se.linkon.petra.gtssales.journeyadvicepricequotes.overview.data.v1_17.GetJourneyAdviceOverviewPriceQuotesSpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation returns passenger categories (and some information about them) to be used for pricequotes and booking.
     * 
     */
    @WebMethod
    @WebResult(name = "GetPassengerCategoriesResponse", targetNamespace = "http://petra.linkon.se/gtssales/passengercategories/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.passengercategories.data.v1_17.GetPassengerCategoriesResponse getPassengerCategories(
        @WebParam(partName = "parameters", name = "GetPassengerCategoriesRequest", targetNamespace = "http://petra.linkon.se/gtssales/passengercategories/data/v1_17")
        se.linkon.petra.gtssales.passengercategories.data.v1_17.GetPassengerCategoriesRequest parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation returns pricegroups.
     *               
     */
    @WebMethod
    @WebResult(name = "GetPriceGroupsDescription", targetNamespace = "http://petra.linkon.se/gtssales/pricegroups/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.pricegroups.data.v1_17.GetPriceGroupsDescription getPriceGroups(
        @WebParam(partName = "parameters", name = "GetPriceGroupsSpecification", targetNamespace = "http://petra.linkon.se/gtssales/pricegroups/data/v1_17")
        se.linkon.petra.gtssales.pricegroups.data.v1_17.GetPriceGroupsSpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation is responsible for retrieving detailed
     * results regarding availability on ground travel services.
     * (trains, buses, etc.)
     *             
     */
    @WebMethod
    @WebResult(name = "GetSeatAvailabilityDetailResponse", targetNamespace = "http://petra.linkon.se/gtssales/seatavailability/detail/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.seatavailability.detail.data.v1_17.GetSeatAvailabilityDetailResponse getSeatAvailabilityDetail(
        @WebParam(partName = "parameters", name = "GetSeatAvailabilityDetailSpecification", targetNamespace = "http://petra.linkon.se/gtssales/seatavailability/detail/data/v1_17")
        se.linkon.petra.gtssales.seatavailability.detail.data.v1_17.GetSeatAvailabilityDetailSpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * Get alternative relations for use with multiride tickets.
     */
    @WebMethod
    @WebResult(name = "MultiRideAlternativeRelationsDescription", targetNamespace = "http://petra.linkon.se/gtssales/multiridealternativerelations/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.multiridealternativerelations.data.v1_17.MultiRideAlternativeRelationsDescription getMultiRideAlternativeRelations(
        @WebParam(partName = "parameters", name = "MultiRideAlternativeRelationsSpecification", targetNamespace = "http://petra.linkon.se/gtssales/multiridealternativerelations/data/v1_17")
        se.linkon.petra.gtssales.multiridealternativerelations.data.v1_17.MultiRideAlternativeRelationsSpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation validates if a promotion code exists or not.
     *    
     */
    @WebMethod
    @WebResult(name = "ValidatePromotionCodeResponse", targetNamespace = "http://petra.linkon.se/gtssales/validatepromotioncode/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.validatepromotioncode.data.v1_17.ValidatePromotionCodeResponse validatePromotionCode(
        @WebParam(partName = "parameters", name = "ValidatePromotionCodeRequest", targetNamespace = "http://petra.linkon.se/gtssales/validatepromotioncode/data/v1_17")
        se.linkon.petra.gtssales.validatepromotioncode.data.v1_17.ValidatePromotionCodeRequest parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation gets a detailed price quote for a segment according to the request.
     */
    @WebMethod
    @WebResult(name = "DetailedSegmentPriceQuoteResponse", targetNamespace = "http://petra.linkon.se/gtssales/detailedpricequote/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.detailedpricequote.data.v1_17.DetailedSegmentPriceQuoteResponse detailedSegmentPriceQuote(
        @WebParam(partName = "parameters", name = "DetailedSegmentPriceQuoteQuery", targetNamespace = "http://petra.linkon.se/gtssales/detailedpricequote/data/v1_17")
        se.linkon.petra.gtssales.detailedpricequote.data.v1_17.DetailedSegmentPriceQuoteQuery parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation returns the valid (relevant) code lists for this service.
     *             
     */
    @WebMethod
    @WebResult(name = "GetValidCodesResponse", targetNamespace = "http://petra.linkon.se/gtssales/validcodes/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.validcodes.data.v1_17.GetValidCodesResponse getValidCodes(
        @WebParam(partName = "parameters", name = "GetValidCodesRequest", targetNamespace = "http://petra.linkon.se/gtssales/validcodes/data/v1_17")
        se.linkon.petra.gtssales.validcodes.data.v1_17.GetValidCodesRequest parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation is responsible for retrieving information about 'optionals'
     * availabilities. 
     * 'Optionals' in this case are for example breakfast, sandwiches or cold dishes.
     *             
     */
    @WebMethod
    @WebResult(name = "GetOptionAvailabilityResponse", targetNamespace = "http://petra.linkon.se/gtssales/optionavailability/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.optionavailability.data.v1_17.GetOptionAvailabilityResponse getOptionAvailability(
        @WebParam(partName = "parameters", name = "GetOptionAvailabilityRequest", targetNamespace = "http://petra.linkon.se/gtssales/optionavailability/data/v1_17")
        se.linkon.petra.gtssales.optionavailability.data.v1_17.GetOptionAvailabilityRequest parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation returns a detailed journey advice price quote using sales
     * categories.
     *               
     */
    @WebMethod
    @WebResult(name = "GetJourneyAdviceDetailedPriceQuotesDescription", targetNamespace = "http://petra.linkon.se/gtssales/journeyadvicepricequotes/detailed/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.journeyadvicepricequotes.detailed.data.v1_17.GetJourneyAdviceDetailedPriceQuotesDescription getJourneyAdviceDetailedPriceQuotes(
        @WebParam(partName = "parameters", name = "GetJourneyAdviceDetailedPriceQuotesSpecification", targetNamespace = "http://petra.linkon.se/gtssales/journeyadvicepricequotes/detailed/data/v1_17")
        se.linkon.petra.gtssales.journeyadvicepricequotes.detailed.data.v1_17.GetJourneyAdviceDetailedPriceQuotesSpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;

    /**
     * The operation books an itinerary service according to the request.
     *             
     */
    @WebMethod
    @WebResult(name = "BookItineraryDescription", targetNamespace = "http://petra.linkon.se/gtssales/booktransport/data/v1_17", partName = "result")
    public se.linkon.petra.gtssales.booktransport.data.v1_17.BookItineraryDescription bookItinerary(
        @WebParam(partName = "parameters", name = "BookItinerarySpecification", targetNamespace = "http://petra.linkon.se/gtssales/booktransport/data/v1_17")
        se.linkon.petra.gtssales.booktransport.data.v1_17.BookItinerarySpecification parameters,
        @WebParam(partName = "clientInformationHeader", name = "ClientInformation", targetNamespace = "http://petra.linkon.se/commoncomplexelements/data/v4_6", header = true)
        se.linkon.petra.commoncomplexelements.data.v4_6.ClientInformation clientInformationHeader
    ) throws GtsSalesException;
}
