package se.linkon.service.gtssales.v1_17;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-29T15:04:03.688+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "WSGtsSalesService", 
                  wsdlLocation = "classpath:wsdl/gtssales/1_17/GtsSalesService.wsdl",
                  targetNamespace = "http://service.linkon.se/gtssales/v1_17") 
public class WSGtsSalesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.linkon.se/gtssales/v1_17", "WSGtsSalesService");
    public final static QName WSGtsSalesPort = new QName("http://service.linkon.se/gtssales/v1_17", "WSGtsSales-port");
    static {
        URL url = WSGtsSalesService.class.getClassLoader().getResource("wsdl/gtssales/1_17/GtsSalesService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(WSGtsSalesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/gtssales/1_17/GtsSalesService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public WSGtsSalesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSGtsSalesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSGtsSalesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSGtsSalesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSGtsSalesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSGtsSalesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GtsSalesService
     */
    @WebEndpoint(name = "WSGtsSales-port")
    public GtsSalesService getWSGtsSalesPort() {
        return super.getPort(WSGtsSalesPort, GtsSalesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GtsSalesService
     */
    @WebEndpoint(name = "WSGtsSales-port")
    public GtsSalesService getWSGtsSalesPort(WebServiceFeature... features) {
        return super.getPort(WSGtsSalesPort, GtsSalesService.class, features);
    }

}
